[build]
  command = "npx prisma db push && remix build"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@remix-run/react", "react", "react-dom"]
  
[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
